In [1]:
import numpy as np

# numpy 基本属性

In [2]:
arr = np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [3]:
arr.shape

(5, 5)

In [4]:
arr.size

25

In [5]:
arr.dtype

dtype('int32')

# numpy 创建数组

## 随机数创建

#### random.rand() 
#生成的是0，1均值分布的随机数
#random.randn() 与rand用法一致，区别:生成的是标准正太分布的随机数

In [6]:
np.random.seed(0)
rand_1 = np.random.rand()
rand_1

0.5488135039273248

In [7]:
rand_2 = np.random.rand(4)
rand_2

array([0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [8]:
rand_3 = np.random.rand(3,4)
rand_3

array([[0.64589411, 0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492, 0.56804456],
       [0.92559664, 0.07103606, 0.0871293 , 0.0202184 ]])

In [9]:
rand_3 = np.random.rand(3,1,4)
rand_3

array([[[0.83261985, 0.77815675, 0.87001215, 0.97861834]],

       [[0.79915856, 0.46147936, 0.78052918, 0.11827443]],

       [[0.63992102, 0.14335329, 0.94466892, 0.52184832]]])

#### random.random_sample
#生成的0，1随机数
#random.random() 用法一致，生成的数也是一致
#standard_normal(),用法一致，生成的是标准的正太分布

In [10]:
rs_1 = np.random.random_sample()
rs_1

0.4146619399905236

In [11]:
rs_2 = np.random.random_sample(4)
rs_2

array([0.26455561, 0.77423369, 0.45615033, 0.56843395])

In [12]:
#生成矩阵就不同 （）
rs_3 = np.random.random_sample((3,4))
rs_3

array([[0.0187898 , 0.6176355 , 0.61209572, 0.616934  ],
       [0.94374808, 0.6818203 , 0.3595079 , 0.43703195],
       [0.6976312 , 0.06022547, 0.66676672, 0.67063787]])

In [13]:
random = np.random.random()
random

0.2103825610738409

In [14]:
random2 = np.random.random(4)
random2

array([0.1289263 , 0.31542835, 0.36371077, 0.57019677])

In [15]:
random2 = np.random.random((4,4))
random2

array([[0.43860151, 0.98837384, 0.10204481, 0.20887676],
       [0.16130952, 0.65310833, 0.2532916 , 0.46631077],
       [0.24442559, 0.15896958, 0.11037514, 0.65632959],
       [0.13818295, 0.19658236, 0.36872517, 0.82099323]])

In [16]:
#### random.randint

In [17]:
randint = np.random.randint(1)
randint

0

In [18]:
randint2 = np.random.randint(4)
randint2

0

In [19]:
randint3 = np.random.randint(2,5,(2))
randint3

array([3, 4])

In [20]:
randint3 = np.random.randint(2,5,(2,4))
randint3

array([[2, 4, 2, 3],
       [4, 4, 3, 2]])

In [21]:
#### standard_normal  

In [22]:
stn = np.random.standard_normal()
stn

1.4759898324822718

In [23]:
stn2 = np.random.standard_normal(2)
stn2

array([ 0.6467801 , -0.36433431])

In [24]:
stn3 = np.random.standard_normal((2,4))
stn3

array([[-0.67877739, -0.35362786, -0.74074747, -0.67502183],
       [-0.13278426,  0.61980106,  1.79116846,  0.17100044]])

#### np.ones ,np.zeros

In [25]:
a = np.ones((1,4))
a

array([[1., 1., 1., 1.]])

In [26]:
a = np.zeros((1,4))
a

array([[0., 0., 0., 0.]])

# np arange() linspace

In [27]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
#linspace 切片 numpy 版本不同，可能有整数和小数之分
arr_lin  = np.linspace(1,20,100).reshape(10,10).astype('int')
arr_lin  = np.linspace(1,20,100,dtype='int').reshape(10,10)
arr_lin

array([[ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2],
       [ 2,  3,  3,  3,  3,  3,  4,  4,  4,  4],
       [ 4,  5,  5,  5,  5,  5,  5,  6,  6,  6],
       [ 6,  6,  7,  7,  7,  7,  7,  8,  8,  8],
       [ 8,  8,  9,  9,  9,  9,  9, 10, 10, 10],
       [10, 10, 10, 11, 11, 11, 11, 11, 12, 12],
       [12, 12, 12, 13, 13, 13, 13, 13, 14, 14],
       [14, 14, 14, 15, 15, 15, 15, 15, 15, 16],
       [16, 16, 16, 16, 17, 17, 17, 17, 17, 18],
       [18, 18, 18, 18, 19, 19, 19, 19, 19, 20]])

In [29]:
arr_arr = np.array([[1,2,3,4,5,6,],[1,2,3,4,5,6,]])
arr_arr

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

# np 切片 \查询\ 筛选

### 切片

In [30]:
arr_c = arr_lin[1:3,2:8]
arr_c

array([[3, 3, 3, 3, 4, 4],
       [5, 5, 5, 5, 5, 6]])

In [31]:
arr_c2 = arr_lin[1:3,0:-1]
arr_c2

array([[2, 3, 3, 3, 3, 3, 4, 4, 4],
       [4, 5, 5, 5, 5, 5, 5, 6, 6]])

In [32]:
arr_c3 = arr_lin[1:3,0:-3]
arr_c3

array([[2, 3, 3, 3, 3, 3, 4],
       [4, 5, 5, 5, 5, 5, 5]])

In [33]:
#列间隔取
arr_c4 = arr_lin[1:3,0:-3:2]
arr_c4

array([[2, 3, 3, 4],
       [4, 5, 5, 5]])

#### np.where

In [34]:
arr_wh = arr_lin[np.where(arr_lin>4)]
arr_wh

array([ 5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  8,
        8,  8,  8,  8,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 11, 11,
       11, 11, 11, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 14, 14, 14, 14,
       14, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17,
       18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 20])

In [35]:
arr_wh2 =  np.where(arr_lin>4,0,"#")# 满足为0，不满足为#
arr_wh2

array([['#', '#', '#', '#', '#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#', '#', '#', '#', '#'],
       ['#', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
       ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
       ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
       ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
       ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
       ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
       ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
       ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0']], dtype='<U11')

# np 修改

In [36]:
#### np 深度拷贝

In [37]:
arr_mv = arr_lin.copy()

In [38]:
##修改值

arr_mv[arr_mv<5]=2
arr_mv

array([[ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  5,  5,  5,  5,  5,  5,  6,  6,  6],
       [ 6,  6,  7,  7,  7,  7,  7,  8,  8,  8],
       [ 8,  8,  9,  9,  9,  9,  9, 10, 10, 10],
       [10, 10, 10, 11, 11, 11, 11, 11, 12, 12],
       [12, 12, 12, 13, 13, 13, 13, 13, 14, 14],
       [14, 14, 14, 15, 15, 15, 15, 15, 15, 16],
       [16, 16, 16, 16, 17, 17, 17, 17, 17, 18],
       [18, 18, 18, 18, 19, 19, 19, 19, 19, 20]])

In [39]:
arr_mv[0,:]=0
arr_mv

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  5,  5,  5,  5,  5,  5,  6,  6,  6],
       [ 6,  6,  7,  7,  7,  7,  7,  8,  8,  8],
       [ 8,  8,  9,  9,  9,  9,  9, 10, 10, 10],
       [10, 10, 10, 11, 11, 11, 11, 11, 12, 12],
       [12, 12, 12, 13, 13, 13, 13, 13, 14, 14],
       [14, 14, 14, 15, 15, 15, 15, 15, 15, 16],
       [16, 16, 16, 16, 17, 17, 17, 17, 17, 18],
       [18, 18, 18, 18, 19, 19, 19, 19, 19, 20]])

### 修改数据类型

In [40]:
arr_ty = arr_lin.copy()
arr_ty = arr_ty.astype('float')
arr_ty

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.],
       [ 2.,  3.,  3.,  3.,  3.,  3.,  4.,  4.,  4.,  4.],
       [ 4.,  5.,  5.,  5.,  5.,  5.,  5.,  6.,  6.,  6.],
       [ 6.,  6.,  7.,  7.,  7.,  7.,  7.,  8.,  8.,  8.],
       [ 8.,  8.,  9.,  9.,  9.,  9.,  9., 10., 10., 10.],
       [10., 10., 10., 11., 11., 11., 11., 11., 12., 12.],
       [12., 12., 12., 13., 13., 13., 13., 13., 14., 14.],
       [14., 14., 14., 15., 15., 15., 15., 15., 15., 16.],
       [16., 16., 16., 16., 17., 17., 17., 17., 17., 18.],
       [18., 18., 18., 18., 19., 19., 19., 19., 19., 20.]])

In [41]:
### 修改nan异常值
### 把一个值改为nan 时，首先这个值必须是float类型
### inf 也同一个道理

In [42]:
### 把一个值改为nan 时，首先这个值必须是float类型
arr_na = arr_lin.copy().astype('float')
arr_na[0:1,:]=np.nan
arr_na

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [ 2.,  3.,  3.,  3.,  3.,  3.,  4.,  4.,  4.,  4.],
       [ 4.,  5.,  5.,  5.,  5.,  5.,  5.,  6.,  6.,  6.],
       [ 6.,  6.,  7.,  7.,  7.,  7.,  7.,  8.,  8.,  8.],
       [ 8.,  8.,  9.,  9.,  9.,  9.,  9., 10., 10., 10.],
       [10., 10., 10., 11., 11., 11., 11., 11., 12., 12.],
       [12., 12., 12., 13., 13., 13., 13., 13., 14., 14.],
       [14., 14., 14., 15., 15., 15., 15., 15., 15., 16.],
       [16., 16., 16., 16., 17., 17., 17., 17., 17., 18.],
       [18., 18., 18., 18., 19., 19., 19., 19., 19., 20.]])

In [43]:
##修改
arr_na[np.isnan(arr_na)]=2
arr_na

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  3.,  3.,  3.,  3.,  3.,  4.,  4.,  4.,  4.],
       [ 4.,  5.,  5.,  5.,  5.,  5.,  5.,  6.,  6.,  6.],
       [ 6.,  6.,  7.,  7.,  7.,  7.,  7.,  8.,  8.,  8.],
       [ 8.,  8.,  9.,  9.,  9.,  9.,  9., 10., 10., 10.],
       [10., 10., 10., 11., 11., 11., 11., 11., 12., 12.],
       [12., 12., 12., 13., 13., 13., 13., 13., 14., 14.],
       [14., 14., 14., 15., 15., 15., 15., 15., 15., 16.],
       [16., 16., 16., 16., 17., 17., 17., 17., 17., 18.],
       [18., 18., 18., 18., 19., 19., 19., 19., 19., 20.]])

#### 修改 inf

In [44]:
### 把一个值改为 inf 时，首先这个值必须是float类型
arr_inf = arr_lin.copy().astype('float')
arr_inf[0:1,:]=np.inf
arr_inf

array([[inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [ 2.,  3.,  3.,  3.,  3.,  3.,  4.,  4.,  4.,  4.],
       [ 4.,  5.,  5.,  5.,  5.,  5.,  5.,  6.,  6.,  6.],
       [ 6.,  6.,  7.,  7.,  7.,  7.,  7.,  8.,  8.,  8.],
       [ 8.,  8.,  9.,  9.,  9.,  9.,  9., 10., 10., 10.],
       [10., 10., 10., 11., 11., 11., 11., 11., 12., 12.],
       [12., 12., 12., 13., 13., 13., 13., 13., 14., 14.],
       [14., 14., 14., 15., 15., 15., 15., 15., 15., 16.],
       [16., 16., 16., 16., 17., 17., 17., 17., 17., 18.],
       [18., 18., 18., 18., 19., 19., 19., 19., 19., 20.]])

In [45]:
arr_inf[np.isinf(arr_inf)]=2
arr_inf

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  3.,  3.,  3.,  3.,  3.,  4.,  4.,  4.,  4.],
       [ 4.,  5.,  5.,  5.,  5.,  5.,  5.,  6.,  6.,  6.],
       [ 6.,  6.,  7.,  7.,  7.,  7.,  7.,  8.,  8.,  8.],
       [ 8.,  8.,  9.,  9.,  9.,  9.,  9., 10., 10., 10.],
       [10., 10., 10., 11., 11., 11., 11., 11., 12., 12.],
       [12., 12., 12., 13., 13., 13., 13., 13., 14., 14.],
       [14., 14., 14., 15., 15., 15., 15., 15., 15., 16.],
       [16., 16., 16., 16., 17., 17., 17., 17., 17., 18.],
       [18., 18., 18., 18., 19., 19., 19., 19., 19., 20.]])

# np 改变形状

In [46]:
arr_sh = arr_lin.copy()
arr_sh2 = arr_sh.reshape(5,20)
arr_sh2

array([[ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,
         4,  4,  4,  4],
       [ 4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,  7,  7,  7,
         7,  8,  8,  8],
       [ 8,  8,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 11, 11, 11,
        11, 11, 12, 12],
       [12, 12, 12, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 15, 15, 15,
        15, 15, 15, 16],
       [16, 16, 16, 16, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 19, 19,
        19, 19, 19, 20]])

### 变成一行

In [47]:
#ravel 改变后子ndarray 元素会影响原来ndarray变化，flatten不会
arr_sh3 = arr_sh.flatten()
arr_sh3

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  4,
        4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,  7,
        7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10, 10, 10, 10,
       10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13,
       14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 17,
       17, 17, 17, 17, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 20])

In [48]:
arr_sh4 = np.append([],arr_sh)
arr_sh4

array([ 1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  2.,  3.,  3.,
        3.,  3.,  3.,  4.,  4.,  4.,  4.,  4.,  5.,  5.,  5.,  5.,  5.,
        5.,  6.,  6.,  6.,  6.,  6.,  7.,  7.,  7.,  7.,  7.,  8.,  8.,
        8.,  8.,  8.,  9.,  9.,  9.,  9.,  9., 10., 10., 10., 10., 10.,
       10., 11., 11., 11., 11., 11., 12., 12., 12., 12., 12., 13., 13.,
       13., 13., 13., 14., 14., 14., 14., 14., 15., 15., 15., 15., 15.,
       15., 16., 16., 16., 16., 16., 17., 17., 17., 17., 17., 18., 18.,
       18., 18., 18., 19., 19., 19., 19., 19., 20.])

# numpy 算术运算（举证的算术运算）

In [50]:
count_arr = arr_lin.copy()
count_arr

array([[ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2],
       [ 2,  3,  3,  3,  3,  3,  4,  4,  4,  4],
       [ 4,  5,  5,  5,  5,  5,  5,  6,  6,  6],
       [ 6,  6,  7,  7,  7,  7,  7,  8,  8,  8],
       [ 8,  8,  9,  9,  9,  9,  9, 10, 10, 10],
       [10, 10, 10, 11, 11, 11, 11, 11, 12, 12],
       [12, 12, 12, 13, 13, 13, 13, 13, 14, 14],
       [14, 14, 14, 15, 15, 15, 15, 15, 15, 16],
       [16, 16, 16, 16, 17, 17, 17, 17, 17, 18],
       [18, 18, 18, 18, 19, 19, 19, 19, 19, 20]])

In [ ]:
#### sum 运行  arr.sum(axis=0),np.sum(arr,axis=0)
min
max
mean


In [52]:
ca = count_arr.sum(axis=0)
ca

array([ 91,  93,  95,  98, 100, 100, 102, 105, 107, 110])

In [53]:
ca2 = np.sum(count_arr,axis=0)
ca2

array([ 91,  93,  95,  98, 100, 100, 102, 105, 107, 110])

In [58]:
ca3 = np.sum(count_arr,axis=1)
ca3

array([ 14,  33,  52,  71,  91, 109, 129, 148, 167, 187])

In [59]:
ca3 = ca3.reshape(-1,1)
ca3

array([[ 14],
       [ 33],
       [ 52],
       [ 71],
       [ 91],
       [109],
       [129],
       [148],
       [167],
       [187]])

#### mean

In [60]:
me_arr = np.mean(count_arr,axis=0)
me_arr

array([ 9.1,  9.3,  9.5,  9.8, 10. , 10. , 10.2, 10.5, 10.7, 11. ])

In [61]:
me_arr2 = np.mean(count_arr,axis=1)
me_arr2

array([ 1.4,  3.3,  5.2,  7.1,  9.1, 10.9, 12.9, 14.8, 16.7, 18.7])

#### max

In [62]:
max_arr = np.max(count_arr,axis=0)
max_arr

array([18, 18, 18, 18, 19, 19, 19, 19, 19, 20])

In [63]:
max_arr = np.max(count_arr,axis=1)
max_arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [65]:
np.pi

3.141592653589793

In [66]:
np.e

2.718281828459045

In [67]:
np.ceil(np.array([1.2,2.5]))#向上取整

array([2., 3.])

In [68]:
np.ceil(np.floor([1.2,2.5]))#向下取整

array([1., 2.])

In [69]:
np.around(np.array([1.223,2.232]),2)#四舍五入

array([1.22, 2.23])

In [70]:
np.sqrt(np.array([4,9]))

array([2., 3.])

In [72]:
np.square(np.array([4,9]))

array([16, 81], dtype=int32)

In [74]:
np.power(np.array([4,9]),2)

array([16, 81], dtype=int32)

In [75]:
np.median(count_arr,axis=1)#众数

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [76]:
np.std(count_arr,axis=1)#标准差

array([0.48989795, 0.64031242, 0.6       , 0.7       , 0.7       ,
       0.7       , 0.7       , 0.6       , 0.64031242, 0.64031242])

In [77]:
np.var(count_arr,axis=1)#方差

array([0.24, 0.41, 0.36, 0.49, 0.49, 0.49, 0.49, 0.36, 0.41, 0.41])

In [78]:
np.cumsum(count_arr,axis=1)#累计求和

array([[  1,   2,   3,   4,   5,   6,   8,  10,  12,  14],
       [  2,   5,   8,  11,  14,  17,  21,  25,  29,  33],
       [  4,   9,  14,  19,  24,  29,  34,  40,  46,  52],
       [  6,  12,  19,  26,  33,  40,  47,  55,  63,  71],
       [  8,  16,  25,  34,  43,  52,  61,  71,  81,  91],
       [ 10,  20,  30,  41,  52,  63,  74,  85,  97, 109],
       [ 12,  24,  36,  49,  62,  75,  88, 101, 115, 129],
       [ 14,  28,  42,  57,  72,  87, 102, 117, 132, 148],
       [ 16,  32,  48,  64,  81,  98, 115, 132, 149, 167],
       [ 18,  36,  54,  72,  91, 110, 129, 148, 167, 187]], dtype=int32)

In [79]:
np.argmax(count_arr,axis=1)

array([6, 6, 7, 7, 7, 8, 8, 9, 9, 9], dtype=int64)

In [88]:
# np 四则运算
arr = arr_lin.copy()
arr2 = arr[1:3,:]
print(arr2.shape)
arr2

(2, 10)


array([[2, 3, 3, 3, 3, 3, 4, 4, 4, 4],
       [4, 5, 5, 5, 5, 5, 5, 6, 6, 6]])

In [89]:
arr3 = arr[3:5,:]
print(arr3.shape)
arr3

(2, 10)


array([[ 6,  6,  7,  7,  7,  7,  7,  8,  8,  8],
       [ 8,  8,  9,  9,  9,  9,  9, 10, 10, 10]])

In [84]:
arr2+arr3

array([[ 8,  9, 10, 10, 10, 10, 11, 12, 12, 12],
       [12, 13, 14, 14, 14, 14, 14, 16, 16, 16]])

In [85]:
arr2-arr3

array([[-4, -3, -4, -4, -4, -4, -3, -4, -4, -4],
       [-4, -3, -4, -4, -4, -4, -4, -4, -4, -4]])

In [86]:
arr2*arr3

array([[12, 18, 21, 21, 21, 21, 28, 32, 32, 32],
       [32, 40, 45, 45, 45, 45, 45, 60, 60, 60]])

In [87]:
arr2/arr3

array([[0.33333333, 0.5       , 0.42857143, 0.42857143, 0.42857143,
        0.42857143, 0.57142857, 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.625     , 0.55555556, 0.55555556, 0.55555556,
        0.55555556, 0.55555556, 0.6       , 0.6       , 0.6       ]])

# 矩阵乘法

In [91]:
arr4 = arr3.reshape(-1,2)
arr4

array([[ 6,  6],
       [ 7,  7],
       [ 7,  7],
       [ 7,  8],
       [ 8,  8],
       [ 8,  8],
       [ 9,  9],
       [ 9,  9],
       [ 9, 10],
       [10, 10]])

In [92]:
np.dot(arr2,arr4)# 与matmul相同

array([[271, 278],
       [422, 433]])

In [93]:
np.matmul(arr2,arr4)

array([[271, 278],
       [422, 433]])

In [94]:
np.multiply(arr2,arr3)#与arr2*arr3等同，矩阵对应元素想成

array([[12, 18, 21, 21, 21, 21, 28, 32, 32, 32],
       [32, 40, 45, 45, 45, 45, 45, 60, 60, 60]])

# np 合并与拼接
"""
np.concatenate([arr,arr2],axis=1)
np.hstack(arr,arr2)
np.c_[arr,arr2]
"""

In [105]:
np.concatenate([arr2,arr3],axis=0)#可按列 也可按行

array([[ 2,  3,  3,  3,  3,  3,  4,  4,  4,  4],
       [ 4,  5,  5,  5,  5,  5,  5,  6,  6,  6],
       [ 6,  6,  7,  7,  7,  7,  7,  8,  8,  8],
       [ 8,  8,  9,  9,  9,  9,  9, 10, 10, 10]])

In [99]:
np.hstack([arr2,arr3])#按列拼接

array([[ 2,  3,  3,  3,  3,  3,  4,  4,  4,  4,  6,  6,  7,  7,  7,  7,
         7,  8,  8,  8],
       [ 4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  8,  8,  9,  9,  9,  9,
         9, 10, 10, 10]])

In [100]:
np.vstack([arr2,arr3])#按行拼接

array([[ 2,  3,  3,  3,  3,  3,  4,  4,  4,  4],
       [ 4,  5,  5,  5,  5,  5,  5,  6,  6,  6],
       [ 6,  6,  7,  7,  7,  7,  7,  8,  8,  8],
       [ 8,  8,  9,  9,  9,  9,  9, 10, 10, 10]])

In [103]:
np.c_[arr2,arr3]#按列拼接

array([[ 2,  3,  3,  3,  3,  3,  4,  4,  4,  4,  6,  6,  7,  7,  7,  7,
         7,  8,  8,  8],
       [ 4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  8,  8,  9,  9,  9,  9,
         9, 10, 10, 10]])

In [ ]:
#8、numpy默认是科学计数法存数据格式，怎么改成float
#np.set_printopition(supress=True)
#限制打印数量          threshold=6
#恢复打印限制          threshold=np.nan

In [ ]:
#csv文件读取 保存

In [106]:
data = np.genfromtxt(path, delimiter=',', skip_header=1, filling_values=-999, dtype=float)
##  csv文件保存
path = r'D:\xxxxx.csv'
np.savetxt(path, data, delimiter=",",fmt='%10.5f',header=' name,age,addr,contry,hoby')

#1、npy文件保存和读取
np.save('myarray.npy',data)
myarray = np.load('myarray.npy')
#2、npz文件保存和读取
#savez to save ndarray
arr1 = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1,10).reshape(2,-1)
np.savez('myndarray_npz.npz',arr1,arr2)
#load npz
arr_npz = np.load('myndarray_npz.npz')
# get npz data  eg arr_npz['arr_0']  arr_npz['arr_n']
arr1_from_npz = arr_npz['arr_0']

NameError: name 'path' is not defined